
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v10-{{ checksum "package-lock.json" }}

      - run: npm ci

      # run tests!
      - run: npm run coverage

      - save_cache:
          paths:
            - ~/.npm
          key: node-v12-{{ checksum "package-lock.json" }}

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
